import "./globals.css";
import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import { Header } from "./components/header";
import Footer from "./components/footer";
import ReduxProvider from "@/redux/provider";
import MobileMenu from "./components/mobile_menu";

const nunito_sans = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito_sans.className}>
        <ReduxProvider>
          <Header />

          {children}

          <Footer />
          <MobileMenu />
        </ReduxProvider>
      </body>
    </html>
  );
}
